/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fit3077.project.UI;

import com.fit3077.project.UI.cancelBookingForm;
import com.fit3077.project.UI.modifyBookingForm;
import com.fit3077.project.UI.revertBookingForm;
import com.fit3077.project.models.booking.bookingStatus;
import com.fit3077.project.models.booking.Booking;
import com.fit3077.project.models.booking.bookingAPICollection;
import com.fit3077.project.models.booking.bookingCollection;
import javax.swing.JOptionPane;

/**
 * Panel which receptionist will use for assisting customers (Phone calls)
 * Differs from adminBookingPanel as it allows cancellation but not deletion.
 * @author User
 */
public class assistBookingPanel extends javax.swing.JPanel {
    
    Booking selectedBooking;
    
    /**
     * Creates new panel assistBookingPanel
     */
    public assistBookingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bookingIDField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        patientNameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateAndTimeField = new javax.swing.JTextField();
        locationField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        statusField = new javax.swing.JTextField();
        lastModifiedField = new javax.swing.JTextField();
        modifyBookingButton = new javax.swing.JButton();
        cancelBookingButton = new javax.swing.JButton();
        revertBookingButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inputBookingIDField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        searchIDButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inputPINField = new javax.swing.JTextField();
        searchPINButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Booking ID");

        bookingIDField.setEditable(false);

        jLabel6.setText("Patient Name");

        patientNameField.setEditable(false);

        jLabel7.setText("Location");

        jLabel8.setText("Date and time");

        dateAndTimeField.setEditable(false);

        locationField.setEditable(false);

        jLabel9.setText("Status");

        jLabel10.setText("Last Modified");

        statusField.setEditable(false);

        lastModifiedField.setEditable(false);

        modifyBookingButton.setText("Modify");
        modifyBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBookingButtonActionPerformed(evt);
            }
        });

        cancelBookingButton.setText("Cancel");
        cancelBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingButtonActionPerformed(evt);
            }
        });

        revertBookingButton.setText("Revert");
        revertBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revertBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(patientNameField)
                                .addComponent(bookingIDField)
                                .addComponent(dateAndTimeField)
                                .addComponent(locationField)
                                .addComponent(statusField)
                                .addComponent(lastModifiedField, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(modifyBookingButton)
                                .addGap(26, 26, 26)
                                .addComponent(revertBookingButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelBookingButton)))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bookingIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dateAndTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lastModifiedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyBookingButton)
                    .addComponent(cancelBookingButton)
                    .addComponent(revertBookingButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Booking Information");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Booking ID");

        searchIDButton.setText("Search via Booking ID");
        searchIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("PIN code");

        searchPINButton.setText("Search via PIN code");
        searchPINButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPINButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputBookingIDField)
                    .addComponent(inputPINField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchIDButton)
                    .addComponent(searchPINButton))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputBookingIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchIDButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputPINField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPINButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Search booking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Loads booking through its ID
     */
    private void loadBookingByID(String id){
        bookingCollection bCollection = bookingAPICollection.getInstance();
        Booking b = bCollection.getBookingByID(id);
        if (b != null){
            bookingIDField.setText(b.getID());
            dateAndTimeField.setText(b.getDateTime());
            patientNameField.setText(b.getPatient().getFullName());
            locationField.setText(b.getBookSite().getName());
            statusField.setText(b.getBookStatus().toString());
            lastModifiedField.setText(b.getLastModTime());
        }
        selectedBooking = b;
    }
    
    /**
     * Loads booking through its PIN (Unique for each booking)
     */
    private void loadBookingByPIN(String pin){
        bookingCollection bCollection = bookingAPICollection.getInstance();
        Booking b = bCollection.getBookingByPIN(pin);
        if (b != null){
            bookingIDField.setText(b.getID());
            dateAndTimeField.setText(b.getDateTime());
            patientNameField.setText(b.getPatient().getFullName());
            locationField.setText(b.getBookSite().getName());
            statusField.setText(b.getBookStatus().toString());
            lastModifiedField.setText(b.getLastModTime());
        }
        selectedBooking = b;
    }
    
    /**
     * Loads booking via ID and check whether the booking ID is valid
     */
    private void searchIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDButtonActionPerformed
        loadBookingByID(inputBookingIDField.getText());
        if (selectedBooking == null){
            JOptionPane.showMessageDialog(this, "Please enter a valid booking ID", "Request failed",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchIDButtonActionPerformed

    /**
     *  Loads booking via PIN and checks whether the booking PIN is valid
     */
    private void searchPINButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPINButtonActionPerformed
        loadBookingByPIN(inputPINField.getText());
        if (selectedBooking == null){
            JOptionPane.showMessageDialog(this, "Please enter a valid PIN", "Request failed",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchPINButtonActionPerformed

    /**
     * Opens booking modification form after validating booking
     */
    private void modifyBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBookingButtonActionPerformed
        // TODO add your handling code here:
        if (validateBooking()){
            modifyBookingForm form = new modifyBookingForm(selectedBooking);
            form.setVisible(true);
            resetDisplay();
        }
    }//GEN-LAST:event_modifyBookingButtonActionPerformed

    /**
     * Opens booking cancellation form after validating booking
     */
    private void cancelBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingButtonActionPerformed
        // TODO add your handling code here:
        if (validateBooking()){
            if (selectedBooking.getBookStatus() == bookingStatus.CANCELLED){
                JOptionPane.showMessageDialog(this, "Booking already cancelled", "Cancellation failed",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            cancelBookingForm form = new cancelBookingForm(selectedBooking);
            form.setVisible(true);
            resetDisplay();
        }
    }//GEN-LAST:event_cancelBookingButtonActionPerformed

    /**
     * Opens revert booking form after validating booking
     */
    private void revertBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revertBookingButtonActionPerformed
        // TODO add your handling code here:
        if (validateBooking()){
            revertBookingForm form = new revertBookingForm(selectedBooking);
            form.setVisible(true);
            resetDisplay();
        }
    }//GEN-LAST:event_revertBookingButtonActionPerformed

    /**
     * Resets the display after opening forms for users to fill
     */
    private void resetDisplay(){
        bookingIDField.setText("");
        dateAndTimeField.setText("");
        patientNameField.setText("");
        locationField.setText("");
        statusField.setText("");
        lastModifiedField.setText("");
        selectedBooking = null;
    }
    
    /**
     * Checks if a booking is selected and whether the selected booking is valid for modification (based on its status)
     */
    private Boolean validateBooking(){
        if (selectedBooking == null){
            JOptionPane.showMessageDialog(this, "Please search for a booking first", "Request failed",JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (selectedBooking.getBookStatus() == bookingStatus.LAPSED || selectedBooking.getBookStatus() == bookingStatus.COMPLETE){
            JOptionPane.showMessageDialog(this, "Lapsed/Completed bookings can't be modified", "Request failed",JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookingIDField;
    private javax.swing.JButton cancelBookingButton;
    private javax.swing.JTextField dateAndTimeField;
    private javax.swing.JTextField inputBookingIDField;
    private javax.swing.JTextField inputPINField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastModifiedField;
    private javax.swing.JTextField locationField;
    private javax.swing.JButton modifyBookingButton;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JButton revertBookingButton;
    private javax.swing.JButton searchIDButton;
    private javax.swing.JButton searchPINButton;
    private javax.swing.JTextField statusField;
    // End of variables declaration//GEN-END:variables
}
