/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fit3077.project.UI;

import com.fit3077.project.models.booking.Booking;
import com.fit3077.project.models.booking.bookingAPI;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 * Form that allow users to confirm and perform booking cancellation
 * @author User
 */
public class cancelBookingForm extends javax.swing.JFrame {

    Booking currentBooking;
    
    /**
     * Creates new form cancelBookingForm
     */
    public cancelBookingForm(Booking currentBooking) {
        initComponents();
        this.currentBooking = currentBooking;
        testingSiteNameField.setText(String.valueOf(currentBooking.getBookSite().getName()));
        bookingIDField.setText(currentBooking.getID());
        patientNameField.setText(currentBooking.getPatient().getFullName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        patientNameField = new javax.swing.JTextField();
        bookingIDField = new javax.swing.JTextField();
        testingSiteNameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cancel Booking");

        jLabel2.setText("Booking ID");

        jLabel3.setText("Patient name");

        jLabel4.setText("Testing site name");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        patientNameField.setEditable(false);

        bookingIDField.setEditable(false);

        testingSiteNameField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testingSiteNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(45, 45, 45)
                                .addComponent(backButton)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookingIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(testingSiteNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Changes the status of the booking to cancelled on the Web Service API
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        String lastModTime = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(new java.util.Date());
        
        //Creates savepoint
        currentBooking.createSavepoint(lastModTime);

        //Loads additionalInfo data
        String additionalInfo = "{}";
            additionalInfo = "{" +
            "\"QRcode\":\"" + currentBooking.getQRcode() + "\"," +
            "\"testType\":\"" + currentBooking.getTestType() + "\"," +
            "\"homeTest\":" + currentBooking.isHomeTest() + "," +        
            "\"URL\":\"" + " " + "\"," +
            "\"lastModifiedTime\":\"" + lastModTime + "\"," +
            currentBooking.getBookingCaretaker().getMementosJSON() +
            "}";

        //Set status to CANCELLED
        String jsonString = "{" +
            "\"status\":\"" + "CANCELLED" + "\"," +
           "\"additionalInfo\":" + additionalInfo + "" +
           "}";

        // If successful, display success in a message box to display 
        if (bookingAPI.patchBookings(jsonString, currentBooking.getID())){
            JOptionPane.showMessageDialog(this, "Booking successfully cancelled.", "Patching successful",JOptionPane.INFORMATION_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the display
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bookingIDField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JTextField testingSiteNameField;
    // End of variables declaration//GEN-END:variables
}
