/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fit3077.project.UI;

import com.fit3077.project.models.booking.bookingAPI;
import com.fit3077.project.models.booking.bookingAPICollection;
import com.fit3077.project.models.booking.bookingCollection;
import com.fit3077.project.models.user.userAPICollection;
import com.fit3077.project.models.user.User;
import com.fit3077.project.models.testingSite.testingSiteAPICollection;
import com.fit3077.project.models.testingSite.testingSite;
import com.fit3077.project.models.user.userCollection;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Form users will fill to provide the details for online booking
 * @author User
 */
public class onlineBookingForm extends javax.swing.JFrame {

    private User selectedPatient;
    private testingSite selectedTS;
    
    /**
     * Creates new form bookingForm
     */
    public onlineBookingForm(int initialTS) {
        initComponents();
        loadDates();
        if (initialTS != -1){
            testingSiteIDField.setText(String.valueOf(initialTS));
            changeTestingSite();
            Timestamp timestamp = new Timestamp(System.currentTimeMillis());
            bookingCollection bCollection = bookingAPICollection.getInstance();
            updateWaitingTime();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        customerField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        testingSiteNameField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        waitingTimeField = new javax.swing.JTextField();
        testingSiteIDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        changeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dateComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Online booking confirmation");

        jLabel2.setText("Customer name");

        jLabel3.setText("Phone number");

        jLabel5.setText("Waiting time");

        jLabel6.setText("Testing site name");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        customerField.setEditable(false);

        phoneNumberField.setEditable(false);

        testingSiteNameField.setEditable(false);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        waitingTimeField.setEditable(false);

        jLabel4.setText("Testing site ID");

        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Date");

        dateComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dateComboBoxItemStateChanged(evt);
            }
        });

        jLabel8.setText("Patient username");

        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testingSiteNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(changeButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(waitingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(testingSiteIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customerField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(submitButton)
                                        .addGap(72, 72, 72)
                                        .addComponent(cancelButton))
                                    .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(findButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testingSiteIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(changeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(testingSiteNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(waitingTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Posts the booking to the web service
     */
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (selectedPatient == null){
            JOptionPane.showMessageDialog(this, "Please enter a username and click find to retrieve user", "Submit failed",JOptionPane.INFORMATION_MESSAGE);
        } else if (selectedTS == null){
            JOptionPane.showMessageDialog(this, "Please select a testing site before submit", "Submit failed",JOptionPane.INFORMATION_MESSAGE);
        } else if (!selectedTS.getOnSiteTesting()){
            JOptionPane.showMessageDialog(this, "Selected testing site does not provide on-site testing", "Submit failed",JOptionPane.INFORMATION_MESSAGE);
        }else{
            String alphabet = "abcdefghijklmnopqrstuvwxyz";
            StringBuilder sb = new StringBuilder();
            Random rng = new Random();
            for(int i = 0; i < 10; i++) {

                // generate random index number
                int index = rng.nextInt(alphabet.length());

                // get character specified by index
                // from the string
                char randomChar = alphabet.charAt(index);

                // append the character to string builder
                sb.append(randomChar);
            }
            String QRcode = sb.toString();
            String lastModTime = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(new java.util.Date());
            //Added savepoints for Assignment 3
            String additionalInfo = "{" +
            "\"QRcode\":\"" + QRcode + "\"," +
            "\"testType\":\"" + " " + "\"," +
            "\"homeTest\":" + false + "," +        
            "\"URL\":\"" + " " + "\"," +
            "\"lastModifiedTime\":\"" + lastModTime + "\"," +
            "\"savePoint1\":\"" + "none" + "\"," +
            "\"savePoint2\":\"" + "none" + "\"," +
            "\"savePoint3\":\"" + "none" + "\"" +
            "}";

            String jsonString = "{" +
            "\"customerId\":\"" + selectedPatient.getID() + "\"," +
            "\"testingSiteId\":\"" + selectedTS.getID() + "\"," +
            "\"startTime\":\"" + dateComboBox.getSelectedItem() + "T" + selectedTS.getOpenTime() + ":00.000Z" + "\"," +
            "\"notes\":\"" + " " + "\"," +
            "\"additionalInfo\":" + additionalInfo + "" +
            "}";

            if (bookingAPI.postBookings(jsonString)){
                QRdisplay qrViewer = new QRdisplay(QRcode);
                qrViewer.setVisible(true);
            }
            dispose();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Changes the testingSite via localID
     */
    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
        changeTestingSite();
    }//GEN-LAST:event_changeButtonActionPerformed

    /**
     * Find for the user with the matching username
     */
    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        // TODO add your handling code here:
        userCollection uCollection = userAPICollection.getInstance();
        selectedPatient = uCollection.getUserByUserName(usernameField.getText());
        if (selectedPatient == null){
            JOptionPane.showMessageDialog(this, "Invalid username", "Find failed",JOptionPane.INFORMATION_MESSAGE);
        } else {
            customerField.setText(selectedPatient.getFullName());
            phoneNumberField.setText(selectedPatient.getPhoneNumber());
        }
    }//GEN-LAST:event_findButtonActionPerformed

    /**
     * invokes the updateWaitingTime method when the combo box's selected item changes
     */
    private void dateComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dateComboBoxItemStateChanged
        // TODO add your handling code here:
        if (selectedTS!=null){
            updateWaitingTime();
        }
    }//GEN-LAST:event_dateComboBoxItemStateChanged

    /**
     * Changes the waiting time (Number of booking * 20)
     */
    private void updateWaitingTime(){
        bookingCollection bCollection = bookingAPICollection.getInstance();
        waitingTimeField.setText(String.valueOf(bCollection.getWaitingTime(selectedTS, dateComboBox.getSelectedItem().toString())));
    }
    
    /**
     * Search and replaces the testing site using local ID
     */
    private void changeTestingSite(){
        try{
            testingSiteAPICollection tCollection = testingSiteAPICollection.getInstance();
            int id = Integer.parseInt(testingSiteIDField.getText());
            testingSite tsite = tCollection.getTestingSiteByLocalID(id);
            if (tsite == null){
                JOptionPane.showMessageDialog(this, "Invalid testing site ID", "Change failed",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            selectedTS = tsite;
            testingSiteNameField.setText(tsite.getName());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "An error occured", "Error",JOptionPane.ERROR_MESSAGE);
        }
        updateWaitingTime();
    }
    
    /**
     * Loads the dates on the combo box
     */
    private void loadDates(){
        DefaultComboBoxModel<String> cbModel = new DefaultComboBoxModel<>();
        LocalDate date = LocalDate.now();
        for (int i = 0;i < Home.getAdvDays(); i++){
            cbModel.addElement(date.plusDays(i).toString());
        }
        dateComboBox.setModel(cbModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JTextField customerField;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField testingSiteIDField;
    private javax.swing.JTextField testingSiteNameField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField waitingTimeField;
    // End of variables declaration//GEN-END:variables
}
