/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fit3077.project.UI;

import com.fit3077.project.UI.utils.bookingsListener;
import com.fit3077.project.UI.cancelBookingForm;
import com.fit3077.project.UI.modifyBookingForm;
import com.fit3077.project.UI.revertBookingForm;
import com.fit3077.project.models.booking.bookingStatus;
import com.fit3077.project.models.booking.Booking;
import com.fit3077.project.models.booking.bookingAPICollection;
import com.fit3077.project.models.booking.bookingCollection;
import com.fit3077.project.models.booking.bookingNotification;
import com.fit3077.project.models.user.User;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 * Panel which allows customer to view, modify and cancel their bookings
 * @author User
 */
public class profilePanel extends javax.swing.JPanel implements bookingsListener {

    User currentUser;
    Booking selectedBooking;
    
    /**
     * Creates new panel profilePanel
     */
    public profilePanel(User cUser) {
        initComponents();
        currentUser =cUser;
        JTable table = bookingTable;
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(table.getModel());
        table.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(bookingTable.getColumnCount()-1, SortOrder.DESCENDING));
        sorter.setSortKeys(sortKeys);
        loadBookings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        modifyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        revertButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bookingIDField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        searchModifyButton = new javax.swing.JButton();
        searchCancelButton = new javax.swing.JButton();
        searchRevertButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Patient name", "Date and time", "Location", "Test type", "Status", "Last modified"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookingTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(bookingTable);
        if (bookingTable.getColumnModel().getColumnCount() > 0) {
            bookingTable.getColumnModel().getColumn(0).setMinWidth(200);
            bookingTable.getColumnModel().getColumn(1).setMinWidth(120);
            bookingTable.getColumnModel().getColumn(1).setMaxWidth(120);
            bookingTable.getColumnModel().getColumn(2).setMinWidth(200);
            bookingTable.getColumnModel().getColumn(2).setMaxWidth(200);
            bookingTable.getColumnModel().getColumn(4).setMinWidth(100);
            bookingTable.getColumnModel().getColumn(4).setMaxWidth(100);
            bookingTable.getColumnModel().getColumn(5).setMinWidth(100);
            bookingTable.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        revertButton.setText("Revert");
        revertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(modifyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(revertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyButton)
                    .addComponent(cancelButton)
                    .addComponent(revertButton))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bookings");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Booking ID");

        searchModifyButton.setText("Modify");
        searchModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchModifyButtonActionPerformed(evt);
            }
        });

        searchCancelButton.setText("Cancel");
        searchCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCancelButtonActionPerformed(evt);
            }
        });

        searchRevertButton.setText("Revert");
        searchRevertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRevertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(bookingIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchModifyButton)
                .addGap(13, 13, 13)
                .addComponent(searchRevertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchCancelButton)
                .addContainerGap(473, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bookingIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchModifyButton)
                    .addComponent(searchCancelButton)
                    .addComponent(searchRevertButton))
                .addGap(33, 33, 33))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Search Booking:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Loads customer's bookings to the bookings table
     */
    private void loadBookings(){
        bookingCollection bCollection = bookingAPICollection.getInstance();
        Booking[] bookings = bCollection.getBookingsByUsername(currentUser.getUsername());
        DefaultTableModel model = (DefaultTableModel) bookingTable.getModel();
        model.setNumRows(0);
        if (bookings != null){
            for (Booking b: bookings) {
                try{
                    Object[] row = {
                        b.getID(),
                        b.getPatient().getFullName(),
                        b.getDateTime(),
                        b.getBookSite().getName(),
                        b.getTestType(),
                        b.getBookStatus(),
                        b.getLastModTime()
                    };
                    model.addRow(row);
                } catch (Exception e){
                }
            }
        }
        
    }
    
    /**
     * (Table section)
     * Opens booking modification form after validating the selected booking
     */
    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        if (validateTableSelection()){
            modifyBookingForm form = new modifyBookingForm(selectedBooking);
            form.setVisible(true);
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    /**
     * (Search section)
     * Opens booking modification form after validating the selected booking
     */
    private void searchModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchModifyButtonActionPerformed
        if (validateSearchInput()){
            modifyBookingForm form = new modifyBookingForm(selectedBooking);
            form.setVisible(true);
        }
    }//GEN-LAST:event_searchModifyButtonActionPerformed

    /**
     * (Table section)
     * Opens booking cancellation form after validating the selected booking
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if (validateTableSelection()){
            if (selectedBooking.getBookStatus() == bookingStatus.CANCELLED){
                JOptionPane.showMessageDialog(this, "Booking already cancelled", "Cancellation failed",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            cancelBookingForm form = new cancelBookingForm(selectedBooking);
            form.setVisible(true);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * (Search section)
     * Opens booking cancellation form after validating the selected booking
     */
    private void searchCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCancelButtonActionPerformed
        // TODO add your handling code here:
        if (validateSearchInput()){
            if (selectedBooking.getBookStatus() == bookingStatus.CANCELLED){
                JOptionPane.showMessageDialog(this, "Booking already cancelled", "Cancellation failed",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            cancelBookingForm form = new cancelBookingForm(selectedBooking);
            form.setVisible(true);
        }
    }//GEN-LAST:event_searchCancelButtonActionPerformed

    /**
     * (Search section)
     * Opens revert booking form after validating the selected booking
     */
    private void searchRevertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRevertButtonActionPerformed
        // TODO add your handling code here:
        if (validateSearchInput()){
            revertBookingForm form = new revertBookingForm(selectedBooking);
            form.setVisible(true);
        }
    }//GEN-LAST:event_searchRevertButtonActionPerformed

    /**
     * (Table section)
     * Opens revert booking form after validating the selected booking
     */
    private void revertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revertButtonActionPerformed
        // TODO add your handling code here:
        if (validateTableSelection()){
            revertBookingForm form = new revertBookingForm(selectedBooking);
            form.setVisible(true);
        }
    }//GEN-LAST:event_revertButtonActionPerformed

    /**
     * Validates the booking selected in the table
     */
    private Boolean validateTableSelection(){
        int row = bookingTable.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(this, "Please select a booking first", "Request failed",JOptionPane.INFORMATION_MESSAGE);
            return false;
        } 
        String bookingID = (String)bookingTable.getValueAt(row,0);
        bookingCollection bCollection = bookingAPICollection.getInstance();
        selectedBooking = bCollection.getBookingByID(bookingID);
        return checkBookingUser() && checkBooking();
    } 
    
    /**
     * Validates the booking entered in the search input field
     */
    private Boolean validateSearchInput(){
        if (bookingIDField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a booking ID first", "Request failed",JOptionPane.INFORMATION_MESSAGE);
            return false;
        } 
        bookingCollection bCollection = bookingAPICollection.getInstance();
        String bookingID = bookingIDField.getText();
        selectedBooking = bCollection.getBookingByID(bookingID);
        return checkBooking() && checkBookingUser();
    } 
   
    /**
     * Check if current logged in user is the owner of the booking
     */
    private Boolean checkBookingUser(){
         if (selectedBooking.getPatient().getUsername() == currentUser.getUsername()){
             return true;
         }
         JOptionPane.showMessageDialog(this, "Booking does not belong to current user", "Request failed",JOptionPane.INFORMATION_MESSAGE);
         return false;
    } 
    
    /**
     * Checks if the booking is valid for modifications
     */
    private Boolean checkBooking(){
         if (selectedBooking == null){
             JOptionPane.showMessageDialog(this, "Please enter a valid booking ID", "Request failed",JOptionPane.INFORMATION_MESSAGE);
             return false;
         } else if (selectedBooking.getBookStatus() == bookingStatus.LAPSED || selectedBooking.getBookStatus() == bookingStatus.COMPLETE){
             JOptionPane.showMessageDialog(this, "Lapsed/Completed bookings can't be modified", "Request failed",JOptionPane.INFORMATION_MESSAGE);
             return false;
         }
         return true;
    }
  
   /**
     * (bookingListener class method)
     * Called whenever a change to any bookings is detected.
     * Refreshes the booking table
     */
    public void refreshBookings(bookingNotification bNotification){
        loadBookings();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookingIDField;
    private javax.swing.JTable bookingTable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton revertButton;
    private javax.swing.JButton searchCancelButton;
    private javax.swing.JButton searchModifyButton;
    private javax.swing.JButton searchRevertButton;
    // End of variables declaration//GEN-END:variables
}
